apiVersion: v1
kind: Service
metadata:
  namespace: myproject
  name: nodejs2-ex
spec:
  ports:
  - name: 8080-tcp
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: nodejs-ex
  sessionAffinity: None
  type: ClusterIP